services:
  mysql:
    image: mysql:8.0
    container_name: md-notes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: md_notes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:20
    container_name: md-notes-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: md_notes
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: node:20
    container_name: md-notes-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "4321:4321"
    environment:
      PUBLIC_ASTRO_API_URL: http://backend:3000
      PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  mysql_data:


# docker exec mysql \
#  mysqldump -u app_user -papp_password app_db > db/backup.sql
